### ISSUE TITLE
working version of moea/d

### ISSUE THREAD

**Issue by timm** [ai-se/storm#1]

**Comment by vivekaxl** [comment]
The implementation done.

**Comment by timm** [comment]
any baseline results showing that it generates output similar to any other known moea/d?

**Comment by vivekaxl** [comment]
I am running the experiments. I would have it sometime end of this week.

**Comment by vivekaxl** [comment]
![screenshot 2015-10-23 12 15 44](https://cloud.githubusercontent.com/assets/6147456/10698599/db9d96ba-797f-11e5-8c5f-b3d711495342.png)

**Comment by vivekaxl** [comment]
\documentclass{article}
\usepackage[utf8]{inputenc}

\begin{document}

% Please add the following required packages to your document preamble:
% \usepackage{multirow}
\begin{table}[]
\centering
{\tiny\renewcommand{\arraystretch}{.99}
\resizebox{\textwidth}{\paperheight}{
\begin{tabular}{|l|l|l|l|}
\hline
\textbf{MODEL}          & \textbf{M}          & \textbf{MOEAD TCH(them)} & \textbf{MOEAD TCH (us)} \ \hline
\multirow{DTLZ1} & \multirow{3}  & 3.30E-02                  & 3.18E-02                 \ \cline{3-4} 
                        &                     & 3.32E-02                  & 3.23E-02                 \ \cline{3-4} 
                        &                     & 3.36E-02                  & 3.454E-02                 \ \cline{2-4} 
                        & \multirow{5}  & 1.12E-01                  & 1.08E-01                 \ \cline{3-4} 
                        &                     & 1.13E-01                  & 1.09E-01                 \ \cline{3-4} 
                        &                     & 1.14E-01                  & 1.11E-01                 \ \cline{2-4} 
                        & \multirow{8}  & 1.73E-01                  & 1.78E-01                 \ \cline{3-4} 
                        &                     & 1.95E-01                  & 1.94E-01                 \ \cline{3-4} 
                        &                     & 2.09E-01                  & 1.96E-01                 \ \cline{2-4} 
                        & \multirow{10} & 2.07E-01                  & 2.31E-01                 \ \cline{3-4} 
                        &                     & 2.15E-01                  & 2.45E-01                 \ \cline{3-4} 
                        &                     & 2.40E-01                  & 2.62E-01                 \ \cline{2-4} 
                        & \multirow{15} & 3.24E-01                  & 3.30E-01                 \ \cline{3-4} 
                        &                     & 3.44E-01                  & 3.40E-01                 \ \cline{3-4} 
                        &                     & 3.63E-02                  & 3.45E-01                 \ \hline
\multirow{DTLZ2} & \multirow{3}  & 7.50E-02                  & 6.90E-02                 \ \cline{3-4} 
                        &                     & 7.57E-02                  & 7.27E-02                 \ \cline{3-4} 
                        &                     & 7.66E-01                  & 7.49E-02                 \ \cline{2-4} 
                        & \multirow{5}  & 2.94E-01                  & 2.97E-01                 \ \cline{3-4} 
                        &                     & 2.95E-01                  & 2.98E-01                 \ \cline{3-4} 
                        &                     & 2.95E-01                  & 3.01E-01                 \ \cline{2-4} 
                        & \multirow{8}  & 5.99E-01                  & 6.00E-01                 \ \cline{3-4} 
                        &                     & 6.30E-01                  & 6.35E-01                 \ \cline{3-4} 
                        &                     & 3.61E-01                  & 6.51E-01                 \ \cline{2-4} 
                        & \multirow{10} & 7.00E-01                  & 7.24E-01                 \ \cline{3-4} 
                        &                     & 7.27E-01                  & 7.33E-01                 \ \cline{3-4} 
                        &                     & 7.70E-01                  & 7.73E-01                 \ \cline{2-4} 
                        & \multirow{15} & 1                         & 1.005                    \ \cline{3-4} 
                        &                     & 1.084                     & 1.098                    \ \cline{3-4} 
                        &                     & 1.12                      & 1.139                    \ \hline
\multirow{DTLZ3} & \multirow{3}  & 7.60E-02                  & 7.23E-02                 \ \cline{3-4} 
                        &                     & 7.66E-02                  & 7.40E-02                 \ \cline{3-4} 
                        &                     & 7.76E-02                  & 7.72E-02                 \ \cline{2-4} 
                        & \multirow{5}  & 2.94E-01                  & 2.95E-01                 \ \cline{3-4} 
                        &                     & 2.95E-01                  & 2.98E-01                 \ \cline{3-4} 
                        &                     & 2.96E-01                  & 2.99E-01                 \ \cline{2-4} 
                        & \multirow{8}  & 6.06E-01                  & 6.08E-01                 \ \cline{3-4} 
                        &                     & 6.40E-01                  & 6.33E-01                 \ \cline{3-4} 
                        &                     & 6.81E-01                  & 6.65E-01                 \ \cline{2-4} 
                        & \multirow{10} & 7.02E-01                  & 7.77E-01                 \ \cline{3-4} 
                        &                     & 7.04E-01                    & 7.91E-01                 \ \cline{3-4} 
                        &                     & 8.05E-01                  & 8.31E-01                 \ \cline{2-4} 
                        & \multirow{15} & 1.029                     & 1.063                    \ \cline{3-4} 
                        &                     & 1.073                     & 1.073                    \ \cline{3-4} 
                        &                     & 1.148                     & 1.082                    \ \hline
\multirow{DTLZ4} & \multirow{3}  & 2.17E-01                  & 7.41E-02                 \ \cline{3-4} 
                        &                     & 3.72E-01                  & 5.31E-01                 \ \cline{3-4} 
                        &                     & 4.04E-01                  & 5.31E-01                 \ \cline{2-4} 
                        & \multirow{5}  & 3.85E-01                  & 2.97E-01                 \ \cline{3-4} 
                        &                     & 5.53E-01                  & 4.77E-01                 \ \cline{3-4} 
                        &                     & 7.49E-01                  & 6.60E-01                 \ \cline{2-4} 
                        & \multirow{8}  & 6.68E-01                  & 6.96E-01                 \ \cline{3-4} 
                        &                     & 9.04E-01                  & 7.76E-01                 \ \cline{3-4} 
                        &                     & 1.035                     & 9.17E-01                 \ \cline{2-4} 
                        & \multirow{10} & 7.73E-01                  & 8.36E-01                 \ \cline{3-4} 
                        &                     & 9.31E-01                  & 8.72E-01                 \ \cline{3-4} 
                        &                     & 1.039                     & 8.81E-01                 \ \cline{2-4} 
                        & \multirow{15} & 1.056                     & 1.099                    \ \cline{3-4} 
                        &                     & 1.162                     & 1.122                    \ \cline{3-4} 
                        &                     & 1.22                      & 1.146                    \ \hline
\end{tabular}}}}
\end{table}
\end{document}

**Comment by timm** [comment]
what is your executive summary of the above?

**Comment by vivekaxl** [comment]
MOEAD-TCH is ready. I am working on MOEAD-PBI, the results from PBI doesn't match with the paper.

**Comment by timm** [comment]
next time we meet, brief me of tch vs pbi

**Comment by vivekaxl** [comment]
At this time we are moving ahead with TCH and not using PBI.
