### ISSUE TITLE
hypervolume calculator working

### ISSUE THREAD

**Issue by timm** [ai-se/storm#11]

**Comment by vivekaxl** [comment]
Done!
https://github.com/ai-se/storm/blob/master/PerformanceMetrics/HyperVolume/hypervolume_computer.py

**Comment by vivekaxl** [comment]
Problem Name:  ZDT1
NSGA Percentage:  62.0729754423
SPEA Percentage:  60.9242277898

Problem Name:  ZDT4
NSGA Percentage:  56.6815381771
SPEA Percentage:  50.9553228404

Problem Name:  ZDT3
NSGA Percentage:  61.5333457257
SPEA Percentage:  59.7332428691

Problem Name:  Golinski
NSGA Percentage:  76.8550889758
SPEA Percentage:  76.3175496719

Problem Name:  ZDT6
NSGA Percentage:  21.8701104789
SPEA Percentage:  16.5817056909

**Comment by vivekaxl** [comment]
Problem Name:  ZDT1
NSGA Percentage:  62.0729754423   <----
SPEA Percentage:  60.9242277898   <----

Problem Name:  ZDT4
NSGA Percentage:  56.6815381771
SPEA Percentage:  50.9553228404

Problem Name:  ZDT3
NSGA Percentage:  61.5333457257
SPEA Percentage:  59.7332428691

Problem Name:  Golinski
NSGA Percentage:  76.8550889758
SPEA Percentage:  76.3175496719

Problem Name:  ZDT6
NSGA Percentage:  21.8701104789   <----
SPEA Percentage:  16.5817056909

   <---- Doesn't seem to match Joe's results.
