### ISSUE TITLE
description of STORM

### ISSUE THREAD

**Issue by timm** [ai-se/storm#14]
need some short description of "inside STORM". like

![image](https://cloud.githubusercontent.com/assets/29195/10199538/230eb25e-676f-11e5-9054-51d823f548eb.png)

but formatted to ieee conference standard.

**Comment by vivekaxl** [comment]
[StormDescription.pdf](https://github.com/ai-se/storm/files/18213/StormDescription.pdf)

**Comment by vivekaxl** [comment]
[StormDescription.pdf](https://github.com/ai-se/storm/files/18214/StormDescription.pdf)

**Comment by vivekaxl** [comment]
[StormDescription.pdf](https://github.com/ai-se/storm/files/18839/StormDescription.pdf)
