### ISSUE TITLE
working version of nsga-III, without buncing

### ISSUE THREAD

**Issue by timm** [ai-se/storm#2]
![image](https://cloud.githubusercontent.com/assets/29195/10198935/4c431686-676c-11e5-862f-74fd9d017eed.png)

**Comment by vivekaxl** [comment]
![screenshot 2015-10-17 13 56 03](https://cloud.githubusercontent.com/assets/6147456/10560355/e55f9692-74d6-11e5-810f-8f24759ca32d.png)

**Comment by vivekaxl** [comment]
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{multirow}
\usepackage[table,xcdraw]{xcolor}
\title{workbench}
\author{Vivek Nair}
\date{October 2015}

\begin{document}

\maketitle

\section{Introduction}

% Please add the following required packages to your document preamble:
% \usepackage{multirow}
% \usepackage[table,xcdraw]{xcolor}
% If you use beamer only pass "xcolor=table" option, i.e. \documentclass[xcolor=table]{beamer}
\begin{table}[]
\centering
\label{my-label}
{\tiny\renewcommand{\arraystretch}{.99}
\resizebox{\textwidth}{\paperheight}{
\begin{tabular}{|l|l|l|l|l|}
\hline
Problem                  & M                    & MaxGen                 & NSGAIII(Them)                     & NSGAIII(Us)                      \ \hline
                         &                      &                        & 4.880E-04                         & 1.17E-03                         \ \cline{4-5} 
                         &                      &                        & 1.308E-03                         & 2.48E-03                         \ \cline{4-5} 
                         & \multirow{-3}{_}{3}  & \multirow{-3}{_}{400}  & 4.880E-03                         & 6.25E-03                         \ \cline{2-5} 
                         &                      &                        & 5.116E-04                         & 6.50E-04                         \ \cline{4-5} 
                         &                      &                        & 9.779E-04                         & 8.47E-04                         \ \cline{4-5} 
                         & \multirow{-3}{_}{5}  & \multirow{-3}{_}{600}  & 1.979E-03                         & 2.28E-03                         \ \cline{2-5} 
                         &                      &                        & 2.044E-03                         & 3.60E-03                         \ \cline{4-5} 
                         &                      &                        & 3.979E-03                         & 4.71E-03                         \ \cline{4-5} 
                         & \multirow{-3}{_}{8}  & \multirow{-3}{_}{750}  & 8.721E-03                         & 5.61E-03                         \ \cline{2-5} 
                         &                      &                        & 2.215E-03                         & 3.51E-03                         \ \cline{4-5} 
                         &                      &                        & 3.462E-03                         & 5.02E-03                         \ \cline{4-5} 
                         & \multirow{-3}{_}{10} & \multirow{-3}{_}{1000} & \cellcolor[HTML]{FD6864}6.869E-03 & \cellcolor[HTML]{FD6864}3.14E-02 \ \cline{2-5} 
                         &                      &                        & 2.649E-03                         & 3.70E-03                         \ \cline{4-5} 
                         &                      &                        & 5.063E-03                         & 7.58E-03                         \ \cline{4-5} 
\multirow{-15}{_}{DTLZ1} & \multirow{-3}{_}{15} & \multirow{-3}{_}{1500} & 1.123E-02                         & 1.03E-02                         \ \hline
                         &                      &                        & 1.262E-03                         & 1.10E-03                         \ \cline{4-5} 
                         &                      &                        & 1.357E-03                         & 1.76E-03                         \ \cline{4-5} 
                         & \multirow{-3}{_}{3}  & \multirow{-3}{_}{250}  & 2.114E-03                         & 2.32E-03                         \ \cline{2-5} 
                         &                      &                        & 4.264E-03                         & 4.53E-03                         \ \cline{4-5} 
                         &                      &                        & 4.982E-03                         & 5.53E-03                         \ \cline{4-5} 
                         & \multirow{-3}{_}{5}  & \multirow{-3}{_}{350}  & \cellcolor[HTML]{FD6864}5.862E-03 & \cellcolor[HTML]{FD6864}1.08E-02 \ \cline{2-5} 
                         &                      &                        & 1.371E-02                         & 1.66E-02                         \ \cline{4-5} 
                         &                      &                        & 1.571E-02                         & 1.82E-02                         \ \cline{4-5} 
                         & \multirow{-3}{_}{8}  & \multirow{-3}{_}{500}  & 1.811E-02                         & 1.95E-02                         \ \cline{2-5} 
                         &                      &                        & 1.350E-02                         & 1.69E-02                         \ \cline{4-5} 
                         &                      &                        & 1.528E-02                         & 1.75E-02                         \ \cline{4-5} 
                         & \multirow{-3}{_}{10} & \multirow{-3}{_}{750}  & 1.697E-02                         & 2.08E-02                         \ \cline{2-5} 
                         &                      &                        & 1.360E-02                         & 1.45E-02                         \ \cline{4-5} 
                         &                      &                        & 1.726E-02                         & 2.01E-02                         \ \cline{4-5} 
\multirow{-15}{_}{DTLZ2} & \multirow{-3}{_}{15} & \multirow{-3}{_}{1000} & 2.114E-02                         & 2.55E-02                         \ \hline
                         &                      &                        & \cellcolor[HTML]{FD6864}9.751E-04 & \cellcolor[HTML]{FD6864}1.28E-03 \ \cline{4-5} 
                         &                      &                        & 4.007E-03                         & 4.64E-03                         \ \cline{4-5} 
                         & \multirow{-3}{_}{3}  & \multirow{-3}{_}{1000} & \cellcolor[HTML]{FD6864}6.665E-03 & \cellcolor[HTML]{FD6864}1.74E-02 \ \cline{2-5} 
                         &                      &                        & \cellcolor[HTML]{FD6864}3.086E-03 & \cellcolor[HTML]{FD6864}1.26E-02 \ \cline{4-5} 
                         &                      &                        & \cellcolor[HTML]{FD6864}5.960E-03 & \cellcolor[HTML]{FD6864}1.63E-02 \ \cline{4-5} 
                         & \multirow{-3}{_}{5}  & \multirow{-3}{_}{1000} & \cellcolor[HTML]{FD6864}1.196E-02 & \cellcolor[HTML]{FD6864}1.69E-01 \ \cline{2-5} 
                         &                      &                        & 1.244E-02                         & 2.20E-02                         \ \cline{4-5} 
                         &                      &                        & 2.375E-02                         & 3.47E-02                         \ \cline{4-5} 
                         & \multirow{-3}{_}{8}  & \multirow{-3}{_}{1000} & 9.649E-02                         & 4.15E-02                         \ \cline{2-5} 
                         &                      &                        & \cellcolor[HTML]{FD6864}8.849E-03 & \cellcolor[HTML]{FD6864}1.45E-02 \ \cline{4-5} 
                         &                      &                        & 1.188E-02                         & 1.65E-02                         \ \cline{4-5} 
                         & \multirow{-3}{_}{10} & \multirow{-3}{_}{1500} & 2.083E-02                         & 3.36E-02                         \ \cline{2-5} 
                         &                      &                        & 1.401E-02                         & 2.03E-02                         \ \cline{4-5} 
                         &                      &                        & 2.145E-02                         & 2.94E-02                         \ \cline{4-5} 
\multirow{-15}{_}{DTLZ3} & \multirow{-3}{_}{15} & \multirow{-3}{_}{2000} & 4.195E-02                         & 4.17E-02                         \ \hline
                         &                      &                        & 2.915E-04                         & 9.24E-04                         \ \cline{4-5} 
                         &                      &                        & 5.970E-04                         & 1.40E-03                         \ \cline{4-5} 
                         & \multirow{-3}{_}{3}  & \multirow{-3}{_}{600}  & 4.286E-01                         & 1.93E-03                         \ \cline{2-5} 
                         &                      &                        & \cellcolor[HTML]{FD6864}9.849E-04 & \cellcolor[HTML]{FD6864}1.17E-03 \ \cline{4-5} 
                         &                      &                        & 1.255E-03                         & 1.46E-03                         \ \cline{4-5} 
                         & \multirow{-3}{_}{5}  & \multirow{-3}{_}{1000} & 1.721E-03                         & 1.64E-03                         \ \cline{2-5} 
                         &                      &                        & 5.079E-03                         & 4.36E-03                         \ \cline{4-5} 
                         &                      &                        & 7.054E-03                         & 5.40E-03                         \ \cline{4-5} 
                         & \multirow{-3}{_}{8}  & \multirow{-3}{_}{1250} & 6.051E-01                         & 5.79E-03                         \ \cline{2-5} 
                         &                      &                        & 5.694E-03                         & 4.08E-03                         \ \cline{4-5} 
                         &                      &                        & 6.337E-03                         & 4.87E-03                         \ \cline{4-5} 
                         & \multirow{-3}{_}{10} & \multirow{-3}{_}{2000} & 1.079E-01                         & 5.25E-03                         \ \cline{2-5} 
                         &                      &                        & 7.110E-03                         & 5.61E-03                         \ \cline{4-5} 
                         &                      &                        & 3.431E-03                         & 6.62E-03                         \ \cline{4-5} 
\multirow{-15}{_}{DTLZ4} & \multirow{-3}{_}{15} & \multirow{-3}{_}{3000} & 1.073                             & 8.62E-03                         \ \hline
\end{tabular}}}
\end{table}
\end{document}
