### ISSUE TITLE
GALE0 vs GALE

### ISSUE THREAD

**Issue by vivekaxl** [ai-se/storm#20]
Who is better?
GALE0: Number of members in the  population is 10X = 1000
GALE: Number of members in the population = 100 (Number of generations=20)

**Comment by vivekaxl** [comment]
| Good Gale is Good | Bad non dominated | Ugly Gale0 is Good |
| --- | --- | --- |
| NRP | DTLZ2-3 | DTLZ4-8 |
| DTLZ3-8 |  | DTLZ1-8 |
| DTLZ2-8 |  | DTLZ12-3 |
| DTLZ3-3 |  |  |
| DTLZ1-3 |  |  |
| DTLZ4-5 |  |  |
| DTLZ3-5 |  |  |
| DTLZ2-5 |  |  |

**Comment by vivekaxl** [comment]
DTLZ1-5 is almost the same

**Comment by vivekaxl** [comment]
![figure02_dtlz1_9_5_](https://cloud.githubusercontent.com/assets/6147456/10991108/71a8c276-8428-11e5-9014-19cff90d3929.png)
![figure03_dtlz2_14_5_](https://cloud.githubusercontent.com/assets/6147456/10991106/71a6b198-8428-11e5-87d0-629d3eaa876e.png)
![figure04_dtlz3_14_5_](https://cloud.githubusercontent.com/assets/6147456/10991107/71a8967a-8428-11e5-9dd7-bdebaed656bb.png)
![figure05_dtlz4_14_5_](https://cloud.githubusercontent.com/assets/6147456/10991111/71a9fdbc-8428-11e5-9213-2106772e075f.png)
![figure06_dtlz1_7_3_](https://cloud.githubusercontent.com/assets/6147456/10991109/71a93d32-8428-11e5-8f88-6888d17ac262.png)
![figure07_dtlz2_12_3_](https://cloud.githubusercontent.com/assets/6147456/10991110/71a9cc98-8428-11e5-8bd3-83f19264be54.png)
![figure08_dtlz3_12_3_](https://cloud.githubusercontent.com/assets/6147456/10991112/71ae4d36-8428-11e5-8393-06c29d6ab6d8.png)
![figure09_dtlz4_12_3_](https://cloud.githubusercontent.com/assets/6147456/10991114/71b29986-8428-11e5-838d-9b780c0f3090.png)
![figure10_dtlz1_12_8_](https://cloud.githubusercontent.com/assets/6147456/10991113/71b2613c-8428-11e5-8ce2-5a42eb80812d.png)
![figure11_dtlz2_17_8_](https://cloud.githubusercontent.com/assets/6147456/10991115/71b4afaa-8428-11e5-9c4b-a6570acb4ca7.png)
![figure12_dtlz3_17_8_](https://cloud.githubusercontent.com/assets/6147456/10991117/71b52656-8428-11e5-867b-5c672cbf1022.png)
![figure13_dtlz4_17_8_](https://cloud.githubusercontent.com/assets/6147456/10991116/71b51878-8428-11e5-9a8e-4fe5f697f509.png)
![figure22_nrp_50_5_5_20_120_](https://cloud.githubusercontent.com/assets/6147456/10991118/71b8f704-8428-11e5-8836-bda1d0e94598.png)

**Comment by vivekaxl** [comment]
![figure01_dtlz1_9_5_](https://cloud.githubusercontent.com/assets/6147456/10991245/ccb0fe1c-8429-11e5-9048-794757555727.png)
![figure02_dtlz2_14_5_](https://cloud.githubusercontent.com/assets/6147456/10991246/ccb18b5c-8429-11e5-9c81-fb2912b94091.png)
![figure03_dtlz3_14_5_](https://cloud.githubusercontent.com/assets/6147456/10991247/ccb297a4-8429-11e5-9c6c-e168c7bc2642.png)
![figure04_dtlz4_14_5_](https://cloud.githubusercontent.com/assets/6147456/10991250/ccb5ae08-8429-11e5-8563-b8ac408c6f32.png)
![figure05_dtlz1_7_3_](https://cloud.githubusercontent.com/assets/6147456/10991249/ccb42f9c-8429-11e5-899c-37bfc1e747ed.png)
![figure06_dtlz2_12_3_](https://cloud.githubusercontent.com/assets/6147456/10991248/ccb2a3b6-8429-11e5-87a4-acbba56da9f5.png)
![figure07_dtlz3_12_3_](https://cloud.githubusercontent.com/assets/6147456/10991251/ccbae576-8429-11e5-9434-6860f21192af.png)
![figure08_dtlz4_12_3_](https://cloud.githubusercontent.com/assets/6147456/10991255/ccbed172-8429-11e5-9df3-29127eca937c.png)
![figure09_dtlz1_12_8_](https://cloud.githubusercontent.com/assets/6147456/10991253/ccbc00aa-8429-11e5-8a05-4a9ba3eb6346.png)
![figure10_dtlz2_17_8_](https://cloud.githubusercontent.com/assets/6147456/10991252/ccbbc144-8429-11e5-8898-65247b21aeb9.png)
![figure11_dtlz3_17_8_](https://cloud.githubusercontent.com/assets/6147456/10991254/ccbd3a92-8429-11e5-8a42-8182238a52bd.png)
![figure12_dtlz4_17_8_](https://cloud.githubusercontent.com/assets/6147456/10991256/ccc1e20e-8429-11e5-9283-c610c8690fe3.png)
![figure21_nrp_50_5_5_20_120_](https://cloud.githubusercontent.com/assets/6147456/10991257/ccc5cfd6-8429-11e5-82e7-cc4986a37b2e.png)

**Comment by timm** [comment]
- how do all the optimizers perform on NRP?

**Comment by timm** [comment]
joe said he had to triple the mutation rate for gale to work on DTLZ

**Comment by vivekaxl** [comment]
From the paper
![screenshot 2015-11-06 11 00 18](https://cloud.githubusercontent.com/assets/6147456/11001657/479c9860-8476-11e5-9eb9-b44c740de2bd.png)
Equivalent modification: (in galeMutate())
![screenshot 2015-11-06 11 06 22](https://cloud.githubusercontent.com/assets/6147456/11001694/7724da52-8476-11e5-9b47-76ab759d8a30.png)

I think the modifications are correct according to the paper. What do you think?

**Comment by vivekaxl** [comment]
Please ignore that charts above. I just checked..I had forgotten to set the value of delta to 3. Sorry!

**Comment by vivekaxl** [comment]
GALE_no_mutation : GALE + no mutation (generate new solutions every generation) - Shown in green

![figure01_dtlz1_9_5_](https://cloud.githubusercontent.com/assets/6147456/11126849/0305e364-893f-11e5-9e8a-03ab9813dcac.png)
![figure02_dtlz2_14_5_](https://cloud.githubusercontent.com/assets/6147456/11126846/030313f0-893f-11e5-9319-604e041e0c9a.png)
![figure03_dtlz3_14_5_](https://cloud.githubusercontent.com/assets/6147456/11126847/03035f7c-893f-11e5-9a2f-27a906a2cd13.png)
![figure04_dtlz4_14_5_](https://cloud.githubusercontent.com/assets/6147456/11126848/03047952-893f-11e5-89f1-4b572d2ab831.png)
![figure05_dtlz1_7_3_](https://cloud.githubusercontent.com/assets/6147456/11126845/030279e0-893f-11e5-8f8f-2a8c3c28bd10.png)
![figure06_dtlz2_12_3_](https://cloud.githubusercontent.com/assets/6147456/11126850/030687ec-893f-11e5-8cfb-50af717cae3b.png)
![figure07_dtlz3_12_3_](https://cloud.githubusercontent.com/assets/6147456/11126854/030f2640-893f-11e5-9973-2126d825dce2.png)
![figure08_dtlz4_12_3_](https://cloud.githubusercontent.com/assets/6147456/11126851/030cce0e-893f-11e5-8a44-0b5f8db6b633.png)
![figure09_dtlz1_12_8_](https://cloud.githubusercontent.com/assets/6147456/11126852/030db5e4-893f-11e5-894a-f666d25ce57b.png)
![figure10_dtlz2_17_8_](https://cloud.githubusercontent.com/assets/6147456/11126853/030e38fc-893f-11e5-80a3-097b4d32b5a2.png)
![figure11_dtlz3_17_8_](https://cloud.githubusercontent.com/assets/6147456/11126855/0313d10e-893f-11e5-8f13-41cd2474ed0f.png)
![figure12_dtlz4_17_8_](https://cloud.githubusercontent.com/assets/6147456/11126860/031f8b7a-893f-11e5-93b6-858027712dcd.png)
![figure13_dtlz1_14_10_](https://cloud.githubusercontent.com/assets/6147456/11126856/0317ef14-893f-11e5-9676-047c59b6ac7e.png)
![figure14_dtlz2_19_10_](https://cloud.githubusercontent.com/assets/6147456/11126857/0318c6fa-893f-11e5-906e-e75bbee3988e.png)
![figure15_dtlz3_19_10_](https://cloud.githubusercontent.com/assets/6147456/11126858/031bc792-893f-11e5-9cef-14aac060e63f.png)
![figure16_dtlz4_19_10_](https://cloud.githubusercontent.com/assets/6147456/11126859/031c80d8-893f-11e5-9b6b-978824920ea2.png)
![figure17_dtlz1_19_15_](https://cloud.githubusercontent.com/assets/6147456/11126861/0322ccfe-893f-11e5-9a1b-7a3e9df191bb.png)
![figure18_dtlz2_24_15_](https://cloud.githubusercontent.com/assets/6147456/11126865/03285a70-893f-11e5-8902-4c91a254b62e.png)
![figure19_dtlz3_24_15_](https://cloud.githubusercontent.com/assets/6147456/11126864/03277c2c-893f-11e5-88ac-d1b77cbb8299.png)
![figure20_dtlz4_24_15_](https://cloud.githubusercontent.com/assets/6147456/11126863/03260342-893f-11e5-9be4-5a5f13fe0874.png)
![figure21_web_portal_](https://cloud.githubusercontent.com/assets/6147456/11126866/032bbddc-893f-11e5-8ad9-ef3e4539231e.png)

**Comment by vivekaxl** [comment]
GALE_NO_MUTATION: Gale but no mutation -> GALE who randomly generates solution every generation -> Shown in green.

![figure01_dtlz1_9_5_](https://cloud.githubusercontent.com/assets/6147456/11126899/4409e2c0-893f-11e5-958d-5de790b71ffe.png)
![figure02_dtlz2_14_5_](https://cloud.githubusercontent.com/assets/6147456/11126896/44086cce-893f-11e5-975d-b021a3da0c02.png)
![figure03_dtlz3_14_5_](https://cloud.githubusercontent.com/assets/6147456/11126900/440a2d2a-893f-11e5-9f85-ab6e730b9574.png)
![figure04_dtlz4_14_5_](https://cloud.githubusercontent.com/assets/6147456/11126895/4404b886-893f-11e5-9c8d-3af6a516c450.png)
![figure05_dtlz1_7_3_](https://cloud.githubusercontent.com/assets/6147456/11126898/44099a4a-893f-11e5-9b52-b8687fb95c0d.png)
![figure06_dtlz2_12_3_](https://cloud.githubusercontent.com/assets/6147456/11126897/440903f0-893f-11e5-8e03-888212c5e4b7.png)
![figure07_dtlz3_12_3_](https://cloud.githubusercontent.com/assets/6147456/11126901/440fa246-893f-11e5-9d63-745d2e4f31f2.png)
![figure08_dtlz4_12_3_](https://cloud.githubusercontent.com/assets/6147456/11126902/4417569e-893f-11e5-9a6f-84b7577e2914.png)
![figure09_dtlz1_12_8_](https://cloud.githubusercontent.com/assets/6147456/11126905/4419154c-893f-11e5-86db-96707e6ff4e6.png)
![figure10_dtlz2_17_8_](https://cloud.githubusercontent.com/assets/6147456/11126904/4417bcb0-893f-11e5-8bc1-159c779b2e1c.png)
![figure11_dtlz3_17_8_](https://cloud.githubusercontent.com/assets/6147456/11126903/44177ed0-893f-11e5-9e65-f11e5a3db1f8.png)
![figure12_dtlz4_17_8_](https://cloud.githubusercontent.com/assets/6147456/11126906/4418f972-893f-11e5-96da-941f71fd4c71.png)
![figure21_web_portal_](https://cloud.githubusercontent.com/assets/6147456/11126907/441c05e0-893f-11e5-8c8c-3b4fa481afbd.png)

**Comment by vivekaxl** [comment]
Summary: It looks to be the results of GALE and GALE_NO_MUTATION are similar.
@timm : What do you think?
Code: https://github.com/vivekaxl/THE_JF_EFFECT/tree/master/Algorithms/GALE_no_mutation
