### ISSUE TITLE
Baseline the GALE with the Joe's Paper

### ISSUE THREAD

**Issue by vivekaxl** [ai-se/storm#22]

**Comment by vivekaxl** [comment]
![figure13_dtlz1_20_2_](https://cloud.githubusercontent.com/assets/6147456/11025928/3b9220e8-8670-11e5-896b-b0ca08490c8b.png)
![figure14_dtlz1_20_4_](https://cloud.githubusercontent.com/assets/6147456/11025930/3b938b9a-8670-11e5-9ecd-084e88dbac51.png)
![figure15_dtlz1_20_6_](https://cloud.githubusercontent.com/assets/6147456/11025929/3b92e442-8670-11e5-9f02-142e5984494e.png)
![figure16_dtlz1_20_8_](https://cloud.githubusercontent.com/assets/6147456/11025931/3b953986-8670-11e5-8bab-a7b5b7e26657.png)

**Comment by vivekaxl** [comment]
![figure13_dtlz1_20_2_](https://cloud.githubusercontent.com/assets/6147456/11026038/e49c9096-8671-11e5-89ec-c9b109633b55.png)
![figure14_dtlz1_20_4_](https://cloud.githubusercontent.com/assets/6147456/11026039/e49edc70-8671-11e5-887f-245177939de2.png)
![figure15_dtlz1_20_6_](https://cloud.githubusercontent.com/assets/6147456/11026040/e4a51b30-8671-11e5-9453-a87c36f1e772.png)
![figure16_dtlz1_20_8_](https://cloud.githubusercontent.com/assets/6147456/11026041/e4a5c90e-8671-11e5-9cb5-89c172aedb2c.png)

**Comment by vivekaxl** [comment]
Figures were not near 0 because of the baseline technique. Refer to baselining jmoo_problem.py.

**Comment by timm** [comment]
These are outputs showing significant reduction in goals.
- [ ] Is red GALE or GALE0?
